【進捗報告】20200513 develop yajirusi
yuto-hatano/life-graph pull request #19
Opened 2020-05-13 11:25 UTC by yuto-hatano

# レビュー観点
何をレビューしてもらいたいのか？

# 変更内容／作業内容
 - [ ] 作業内容１
 - [ ] 作業内容２
 - [ ] 作業内容３
〜中略〜
 - [ ] 作業内容Ｎ

# Before（画面に変更がある場合）
変更前のスクリーンショット（イメージ）をドラッグ＆ドロップで貼り付け

# After （画面に変更がある場合）
変更前のスクリーンショット（イメージ）をドラッグ＆ドロップで貼り付け

2020-05-13 14:09 UTC, hidekishibashi requested changes
現状ではマージできないので、朝一対応してください。
理由：
　・api/binディレクトリに結構な差分が入ってしまっているので、マージすると次のPRでも差分として現れるので

後指摘点
・.DS_Storeが入っている
・docker/mysql/data/.gitignoreこの変更は必要？

PRレビューで防げるところ多いので、レビューしっかりしてくださいー

2020-05-13 14:09 UTC, hidekishibashi commented on api/pom.xml
> +		</dependency>
thymeleafは今回使わないです

2020-05-13 14:09 UTC, hidekishibashi commented on api/src/main/java/com/lifegraph/team20/ServletInitializer.java
> +    return application.sources(ApiApplication.class);
このクラスの意図は・・・？

2020-05-13 14:09 UTC, hidekishibashi commented on api/src/main/java/com/lifegraph/team20/WebSecurityConfig.java
> +    http.authorizeRequests().antMatchers("/auth").permitAll().anyRequest().authenticated();
このURL指定は大丈夫？

2020-05-13 14:09 UTC, hidekishibashi commented on api/src/test/java/com/lifegraph/team20/ApiApplicationTests.java
> +  void contextLoads() {
このファイルの意図は？

2020-05-14 01:52 UTC, yuto-hatano commented
> ・api/binディレクトリに結構な差分が入ってしまっているので、マージすると次のPRでも差分として現れるので
↳api/binを削除しました。

> ・.DS_Storeが入っている
↳存在した.DS_Storeを削除し、life-graph配下の.gitignoreに*DS_Storeを追加しました

> ・docker/mysql/data/.gitignoreこの変更は必要？
↳消えてしまった原因は調査しましたが不明でした。意図した変更ではないので石橋さんのファイル構成と同様にしました。

> PRレビューで防げるところ多いので、レビューしっかりしてくださいー
↳承知しました。メンバー自身でもコミット前に確認するようにしてもらいます。

Javaの部分については昨日作業を進めてしまっているので未対応です。
本日の日次報告までに対応を進めます。

よろしくお願い致します。

2020-05-14 02:23 UTC, hidekishibashi approved these changes

2020-05-14 02:23 UTC, hidekishibashi commented on vue/src/views/Header.vue
> +    <router-link to="/top">
```suggestion
    <router-link to="/top" tag="button">
```
の方がシンプルで良いかと！

2020-05-14 02:23 UTC, hidekishibashi commented on vue/src/views/Header.vue
> +      authority: 'Owner'
👍

2020-05-14 04:09 UTC, hidekishibashi approved these changes

2020-05-14 04:09 UTC, merged